USE MASTER
GO

CREATE DATABASE FARMACIA
GO

USE FARMACIA
GO

SET DATEFORMAT DMY
GO


------------------------- PRIMEROS----------------------------
CREATE TABLE PRODUCTO
(
ID_PRODUCTO INT IDENTITY (100, 1) PRIMARY KEY,
NOM_PRODUCTO VARCHAR(20) NOT NULL,
PRESENTACION VARCHAR(15) NOT NULL
				CHECK(PRESENTACION IN('CAJA','BLISTER','UNIDAD')),
LABORATORIO VARCHAR(20) NOT NULL
				CHECK(LABORATORIO IN ('ALCON','ABBOT','BAYER','CIFARMA')),
NUM_LOTE VARCHAR(10) NOT NULL,
FECH_VENCIMIENTO VARCHAR(40) NOT NULL
)
GO

			      
CREATE TABLE PROVEEDOR
(
ID_PROVEEDOR INT IDENTITY (200, 1) PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(40) UNIQUE NOT NULL,
RUC CHAR(10) UNIQUE NOT NULL
)
GO


CREATE TABLE TRABAJADOR
(
ID_TRABAJADOR INT IDENTITY (300, 1) PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
COLEGIATURA VARCHAR(25) NOT NULL
			CHECK(COLEGIATURA IN('QUIMICO FARMACEUTICO','TECNICO FARMACEUTICO')),
SUELDO MONEY NOT NULL
		CHECK(SUELDO>=1025)
)
GO

------------------------- SEGUNDOS ----------------------------

CREATE TABLE KARDEX
(
ID_KARDEX INT IDENTITY (400, 1) PRIMARY KEY,
ID_TRABAJADOR INT FOREIGN KEY REFERENCES TRABAJADOR,
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO,
DETALLLE VARCHAR(30) NOT NULL,
INGRESO VARCHAR(5) NOT NULL,
SALIDA VARCHAR(5) NOT NULL,
FECHA DATE
)
GO

CREATE TABLE CATEGORIA_PRODUCTO
(
ID_CATEGORIAS INT IDENTITY (500, 1) PRIMARY KEY,
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO,
NOMBRE VARCHAR(20) NOT NULL,
NUM_STAND VARCHAR(6) NOT NULL
)
GO



CREATE TABLE ORDEN_PEDIDO
(
ID_COMPRA INT IDENTITY (600, 1) PRIMARY KEY,
ID_PROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR,
NUM_COMPRA VARCHAR(16) NOT NULL,
FECHAR DATE
)
GO

------------------------- TERCERO ----------------------------


CREATE TABLE DETALLE_ORDEN_PEDIDO
(
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO,
ID_COMPRA INT FOREIGN KEY REFERENCES ORDEN_PEDIDO,
CONSTRAINT PK_PRO_OP PRIMARY KEY(ID_PRODUCTO,ID_COMPRA),
NUM_DETALLE VARCHAR(4) NOT NULL,
CANTIDAD VARCHAR(4) NOT NULL,
PRECIO MONEY NOT NULL

)
GO





